# Generated by Django 3.0.4 on 2020-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tz',
            field=models.CharField(blank=True, default='Asia/Kolkata', max_length=1000, null=True),
        ),
    ]
